apiVersion: v1
kind: Service
metadata:
  name: result
  labels:
    name: result-service
    app: demo-result-app
spec:
  type: LoadBalancer    # NodePort when local, and LoadBalancer when deployed remotely
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: result-app-pod
    app: demo-voting-app
    