apiVersion: apps/v1
kind: Deployment

# Defining the deployment
metadata:
  name: nginx-deployment
  labels:
    tier: frontend

# Defining the pod/application/container
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
